apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: target-cluster-minimal
  namespace: default
spec:
  handle: marcin # Do not deploy on mgmt cluster as cert-manager is one of the services.