apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: flux-helm
  namespace: default
spec:
  helm:
    version: "2.12.2"
    chart: flux2
    url: https://fluxcd-community.github.io/helm-charts
  clusterRef:
    kind: Cluster
    name: target-cluster-minimal
    namespace: default
  reconciliation:
    driftDetection: true
    interval: 30s